#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameplan.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PCmobilegameplan")]
	public partial class PersonaMainDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPC2_Email(PC2_Email instance);
    partial void UpdatePC2_Email(PC2_Email instance);
    partial void DeletePC2_Email(PC2_Email instance);
    partial void InsertPC2_EmailType(PC2_EmailType instance);
    partial void UpdatePC2_EmailType(PC2_EmailType instance);
    partial void DeletePC2_EmailType(PC2_EmailType instance);
    #endregion
		
		public PersonaMainDataContext() : 
				base(global::Gameplan.Data.Properties.Settings.Default.PCmobilegameplanConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaMainDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaMainDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaMainDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaMainDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PC2_Email> PC2_Emails
		{
			get
			{
				return this.GetTable<PC2_Email>();
			}
		}
		
		public System.Data.Linq.Table<PC2_EmailTemplate> PC2_EmailTemplates
		{
			get
			{
				return this.GetTable<PC2_EmailTemplate>();
			}
		}
		
		public System.Data.Linq.Table<PC2_EmailType> PC2_EmailTypes
		{
			get
			{
				return this.GetTable<PC2_EmailType>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PC2_Email")]
	public partial class PC2_Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _EmailType;
		
		private int _LanguageID;
		
		private string _SubjectText;
		
		private string _EmailText;
		
		private int _PtnerID;
		
		private int _CompID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEmailTypeChanging(string value);
    partial void OnEmailTypeChanged();
    partial void OnLanguageIDChanging(int value);
    partial void OnLanguageIDChanged();
    partial void OnSubjectTextChanging(string value);
    partial void OnSubjectTextChanged();
    partial void OnEmailTextChanging(string value);
    partial void OnEmailTextChanged();
    partial void OnPtnerIDChanging(int value);
    partial void OnPtnerIDChanged();
    partial void OnCompIDChanging(int value);
    partial void OnCompIDChanged();
    #endregion
		
		public PC2_Email()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailType", DbType="NVarChar(5)")]
		public string EmailType
		{
			get
			{
				return this._EmailType;
			}
			set
			{
				if ((this._EmailType != value))
				{
					this.OnEmailTypeChanging(value);
					this.SendPropertyChanging();
					this._EmailType = value;
					this.SendPropertyChanged("EmailType");
					this.OnEmailTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int NOT NULL")]
		public int LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this.OnLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._LanguageID = value;
					this.SendPropertyChanged("LanguageID");
					this.OnLanguageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectText", DbType="NVarChar(200)")]
		public string SubjectText
		{
			get
			{
				return this._SubjectText;
			}
			set
			{
				if ((this._SubjectText != value))
				{
					this.OnSubjectTextChanging(value);
					this.SendPropertyChanging();
					this._SubjectText = value;
					this.SendPropertyChanged("SubjectText");
					this.OnSubjectTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailText", DbType="NVarChar(MAX)")]
		public string EmailText
		{
			get
			{
				return this._EmailText;
			}
			set
			{
				if ((this._EmailText != value))
				{
					this.OnEmailTextChanging(value);
					this.SendPropertyChanging();
					this._EmailText = value;
					this.SendPropertyChanged("EmailText");
					this.OnEmailTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PtnerID", DbType="Int NOT NULL")]
		public int PtnerID
		{
			get
			{
				return this._PtnerID;
			}
			set
			{
				if ((this._PtnerID != value))
				{
					this.OnPtnerIDChanging(value);
					this.SendPropertyChanging();
					this._PtnerID = value;
					this.SendPropertyChanged("PtnerID");
					this.OnPtnerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompID", DbType="Int NOT NULL")]
		public int CompID
		{
			get
			{
				return this._CompID;
			}
			set
			{
				if ((this._CompID != value))
				{
					this.OnCompIDChanging(value);
					this.SendPropertyChanging();
					this._CompID = value;
					this.SendPropertyChanged("CompID");
					this.OnCompIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PC2_EmailTemplate")]
	public partial class PC2_EmailTemplate
	{
		
		private int _MessageFormatID;
		
		private string _MessageFormat;
		
		private int _LanguageID;
		
		private int _PartnerID;
		
		public PC2_EmailTemplate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageFormatID", DbType="Int NOT NULL")]
		public int MessageFormatID
		{
			get
			{
				return this._MessageFormatID;
			}
			set
			{
				if ((this._MessageFormatID != value))
				{
					this._MessageFormatID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageFormat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MessageFormat
		{
			get
			{
				return this._MessageFormat;
			}
			set
			{
				if ((this._MessageFormat != value))
				{
					this._MessageFormat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int NOT NULL")]
		public int LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this._LanguageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartnerID", DbType="Int NOT NULL")]
		public int PartnerID
		{
			get
			{
				return this._PartnerID;
			}
			set
			{
				if ((this._PartnerID != value))
				{
					this._PartnerID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PC2_EmailType")]
	public partial class PC2_EmailType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _EmailTypeDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEmailTypeDescChanging(string value);
    partial void OnEmailTypeDescChanged();
    #endregion
		
		public PC2_EmailType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTypeDesc", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string EmailTypeDesc
		{
			get
			{
				return this._EmailTypeDesc;
			}
			set
			{
				if ((this._EmailTypeDesc != value))
				{
					this.OnEmailTypeDescChanging(value);
					this.SendPropertyChanging();
					this._EmailTypeDesc = value;
					this.SendPropertyChanged("EmailTypeDesc");
					this.OnEmailTypeDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
